-- Test data generated by Claude AI

-- Use the LeisureAustralasiaDB database
USE LeisureAustralasiaDB;
GO

-- Note: Status, Currency, ServiceType, and FacilityType tables already have seed data

-- Country data
INSERT INTO Country (Name, CountryCode, DefaultCurrencyId, IsActive)
VALUES 
('Australia', 'AUS', 1, 1),
('Singapore', 'SGP', 2, 1),
('Thailand', 'THA', 3, 1),
('Vietnam', 'VNM', 4, 1),
('India', 'IND', 5, 1),
('Sri Lanka', 'LKA', 6, 1);

-- City data
INSERT INTO City (Name, CountryId, IsActive)
VALUES 
('Brisbane', 1, 1),
('Cairns', 1, 1),
('Newcastle', 1, 1),
('Broome', 1, 1),
('Darwin', 1, 1),
('Singapore', 2, 1),
('Bangkok', 3, 1),
('Hanoi', 4, 1),
('Mumbai', 5, 1),
('Colombo', 6, 1);

-- Role data
INSERT INTO Role (Name, Description, CanAuthorizeDiscounts, CanAuthorizePackages, MaxDiscountPercentage)
VALUES 
('Manager', 'Hotel Manager', 1, 1, 25.00),
('Front Desk Supervisor', 'Supervises front desk staff', 1, 0, 15.00),
('Front Desk Agent', 'Handles check-ins and reservations', 0, 0, NULL),
('Housekeeping', 'Housekeeping staff', 0, 0, NULL),
('Food and Beverage', 'Food and beverage staff', 0, 0, NULL);

-- Department data
INSERT INTO Department (Name, Description, IsActive)
VALUES 
('Front Office', 'Front desk and reservations', 1),
('Housekeeping', 'Room cleaning and maintenance', 1),
('Food & Beverage', 'Restaurant and bar services', 1),
('Administration', 'Administrative functions', 1),
('Marketing', 'Marketing and promotions', 1);

-- ServiceCategory data
INSERT INTO ServiceCategory (Code, Name, Description, ServiceTypeId, IsActive)
VALUES 
('ROOM-STD', 'Standard Room', 'Standard room accommodation', 1, 1),
('ROOM-DEL', 'Deluxe Room', 'Deluxe room accommodation', 1, 1),
('ROOM-STE', 'Suite', 'Suite accommodation', 1, 1),
('MEAL-BRK', 'Breakfast', 'Breakfast service', 2, 1),
('MEAL-LUN', 'Lunch', 'Lunch service', 2, 1),
('MEAL-DIN', 'Dinner', 'Dinner service', 2, 1),
('VENUE-CON', 'Conference Room', 'Conference room rental', 3, 1),
('SPA-MAS', 'Massage', 'Massage service', 4, 1),
('TRANS-APT', 'Airport Transfer', 'Transportation to/from airport', 5, 1);

-- PaymentMethod data
INSERT INTO PaymentMethod (Name, Description, IsActive)
VALUES 
('Credit Card', 'Payment via credit card', 1),
('Debit Card', 'Payment via debit card', 1),
('Cash', 'Cash payment', 1),
('Bank Transfer', 'Bank transfer payment', 1),
('Digital Wallet', 'Payment via digital wallet', 1);

-- ChargeType data
INSERT INTO ChargeType (Name, Description, IsActive)
VALUES 
('Room Charge', 'Charge for room accommodation', 1),
('Food & Beverage', 'Charge for food and beverage', 1),
('Facility Usage', 'Charge for using facilities', 1),
('Service', 'Charge for additional services', 1),
('Cancellation Fee', 'Fee for cancellation', 1);

-- Hotel data
INSERT INTO Hotel (Name, Address, CityId, PhoneNumber, Email, Description, TotalCapacity, BaseCurrencyId, IsActive)
VALUES 
('Leisure Brisbane', '123 Queen Street, Brisbane', 1, '+61-7-3000-1000', 'brisbane@leisuregroup.com', 'Luxury hotel in Brisbane CBD', 200, 1, 1),
('Leisure Cairns', '45 Esplanade, Cairns', 2, '+61-7-4000-2000', 'cairns@leisuregroup.com', 'Beachfront resort in Cairns', 150, 1, 1),
('Leisure Newcastle', '78 Hunter St, Newcastle', 3, '+61-2-4900-3000', 'newcastle@leisuregroup.com', 'Business hotel in Newcastle', 120, 1, 1),
('Leisure Singapore', '55 Orchard Road, Singapore', 6, '+65-6123-4567', 'singapore@leisuregroup.com', 'Luxury hotel in Singapore', 250, 2, 1),
('Leisure Bangkok', '123 Sukhumvit Road, Bangkok', 7, '+66-2-123-4567', 'bangkok@leisuregroup.com', 'Resort in Bangkok', 180, 3, 1);

-- Facility data
INSERT INTO Facility (Name, FacilityTypeId, HotelId, Description, Capacity, StatusId, IsActive)
VALUES 
-- Brisbane Hotel Facilities
('Room 101', 1, 1, 'Standard Room - King Bed', 2, 1, 1),
('Room 102', 1, 1, 'Standard Room - Twin Beds', 2, 1, 1),
('Room 201', 2, 1, 'Family Room - 1 King & 2 Singles', 4, 1, 1),
('Suite 301', 3, 1, 'Executive Suite', 2, 1, 1),
('Conference Room A', 4, 1, 'Conference Room with AV equipment', 50, 1, 1),
('Restaurant', 5, 1, 'Main restaurant', 60, 1, 1),
('Swimming Pool', 6, 1, 'Outdoor swimming pool', 30, 1, 1),

-- Cairns Hotel Facilities
('Room C101', 1, 2, 'Standard Room - Ocean View', 2, 1, 1),
('Room C102', 1, 2, 'Standard Room - Garden View', 2, 1, 1),
('Family Suite C201', 2, 2, 'Family Suite with Ocean View', 4, 1, 1),
('Restaurant Coral', 5, 2, 'Seafood restaurant', 40, 1, 1),
('Pool Deck', 6, 2, 'Infinity Pool', 25, 1, 1),

-- Singapore Hotel Facilities
('Room S101', 1, 4, 'Standard Room - City View', 2, 1, 1),
('Room S102', 1, 4, 'Standard Room - Garden View', 2, 1, 1),
('Suite S301', 3, 4, 'Luxury Suite', 2, 1, 1),
('Conference Hall', 4, 4, 'Grand Conference Hall', 100, 1, 1),
('Spa Center', 8, 4, 'Wellness and Spa', 10, 1, 1);

-- Employee data
INSERT INTO Employee (FirstName, LastName, Email, PhoneNumber, RoleId, DepartmentId, HotelId, CanAuthorizeDiscounts, MaxDiscountPercentage, HireDate, IsActive)
VALUES 
-- Brisbane staff
('John', 'Smith', 'john.smith@leisuregroup.com', '+61-400-123-456', 1, 4, 1, 1, 25.00, '2020-01-15', 1),
('Sarah', 'Johnson', 'sarah.johnson@leisuregroup.com', '+61-400-234-567', 2, 1, 1, 1, 15.00, '2021-03-10', 1),
('Michael', 'Lee', 'michael.lee@leisuregroup.com', '+61-400-345-678', 3, 1, 1, 0, NULL, '2022-05-20', 1),

-- Cairns staff
('Emma', 'Brown', 'emma.brown@leisuregroup.com', '+61-400-456-789', 1, 4, 2, 1, 25.00, '2019-11-05', 1),
('David', 'Wilson', 'david.wilson@leisuregroup.com', '+61-400-567-890', 2, 1, 2, 1, 15.00, '2021-02-15', 1),

-- Singapore staff
('Lily', 'Tan', 'lily.tan@leisuregroup.com', '+65-9123-4567', 1, 4, 4, 1, 25.00, '2018-06-10', 1),
('Raj', 'Patel', 'raj.patel@leisuregroup.com', '+65-9234-5678', 3, 1, 4, 0, NULL, '2022-01-15', 1);

-- ServiceItem data
INSERT INTO ServiceItem (Name, Description, ServiceCategoryId, FacilityTypeId, BaseCost, BaseCurrencyId, Capacity, AvailableTimes, Restrictions, Notes, Comments, StatusId, IsActive)
VALUES 
-- Accommodation
('Standard Room', 'Standard room with king or twin beds', 1, 1, 80.00, 1, 2, '24 hours', 'No pets allowed', 'Includes free WiFi', NULL, 1, 1),
('Deluxe Room', 'Spacious deluxe room with city view', 2, 1, 120.00, 1, 2, '24 hours', 'No pets allowed', 'Includes free WiFi and minibar', NULL, 1, 1),
('Family Room', 'Room suitable for families with children', 2, 2, 150.00, 1, 4, '24 hours', 'No pets allowed', 'Includes free WiFi', NULL, 1, 1),
('Executive Suite', 'Luxury suite with separate living area', 3, 3, 250.00, 1, 2, '24 hours', 'No pets allowed', 'Includes free WiFi, minibar, and lounge access', NULL, 1, 1),

-- Meals
('Breakfast Buffet', 'Full breakfast buffet', 4, 5, 15.00, 1, NULL, '6:30 AM - 10:30 AM', NULL, 'International breakfast selection', NULL, 1, 1),
('Lunch Buffet', 'Lunch buffet with international cuisine', 5, 5, 25.00, 1, NULL, '12:00 PM - 2:30 PM', NULL, 'Includes soft drinks', NULL, 1, 1),
('Dinner Buffet', 'Dinner buffet with themed nights', 6, 5, 35.00, 1, NULL, '6:00 PM - 10:00 PM', NULL, 'Includes soft drinks', NULL, 1, 1),

-- Venues
('Half-Day Conference Room', 'Conference room rental for half day', 7, 4, 200.00, 1, 50, '8:00 AM - 12:00 PM or 1:00 PM - 5:00 PM', NULL, 'Includes basic AV equipment', NULL, 1, 1),
('Full-Day Conference Room', 'Conference room rental for full day', 7, 4, 350.00, 1, 50, '8:00 AM - 5:00 PM', NULL, 'Includes basic AV equipment and lunch', NULL, 1, 1),

-- Wellness
('Swedish Massage', '60-minute Swedish massage', 8, 8, 60.00, 1, 1, '10:00 AM - 8:00 PM', NULL, 'Subject to availability', NULL, 1, 1),
('Deep Tissue Massage', '60-minute deep tissue massage', 8, 8, 75.00, 1, 1, '10:00 AM - 8:00 PM', NULL, 'Subject to availability', NULL, 1, 1),

-- Transportation
('Airport Transfer - One Way', 'One-way transfer between hotel and airport', 9, NULL, 30.00, 1, 4, '24 hours', 'Advance booking required', '45-minute journey approximately', NULL, 1, 1),
('Airport Transfer - Return', 'Return transfer between hotel and airport', 9, NULL, 55.00, 1, 4, '24 hours', 'Advance booking required', '45-minute journey approximately', NULL, 1, 1);

-- HotelServiceItem data
INSERT INTO HotelServiceItem (HotelId, ServiceItemId, IsActive)
VALUES 
-- Brisbane Hotel Services
(1, 1, 1), -- Standard Room
(1, 2, 1), -- Deluxe Room
(1, 3, 1), -- Family Room
(1, 4, 1), -- Executive Suite
(1, 5, 1), -- Breakfast Buffet
(1, 6, 1), -- Lunch Buffet
(1, 7, 1), -- Dinner Buffet
(1, 8, 1), -- Half-Day Conference Room
(1, 9, 1), -- Full-Day Conference Room
(1, 12, 1), -- Airport Transfer - One Way
(1, 13, 1), -- Airport Transfer - Return

-- Cairns Hotel Services
(2, 1, 1), -- Standard Room
(2, 2, 1), -- Deluxe Room
(2, 3, 1), -- Family Room
(2, 5, 1), -- Breakfast Buffet
(2, 6, 1), -- Lunch Buffet
(2, 7, 1), -- Dinner Buffet
(2, 12, 1), -- Airport Transfer - One Way
(2, 13, 1), -- Airport Transfer - Return

-- Singapore Hotel Services
(4, 1, 1), -- Standard Room
(4, 2, 1), -- Deluxe Room
(4, 4, 1), -- Executive Suite
(4, 5, 1), -- Breakfast Buffet
(4, 6, 1), -- Lunch Buffet
(4, 7, 1), -- Dinner Buffet
(4, 8, 1), -- Half-Day Conference Room
(4, 9, 1), -- Full-Day Conference Room
(4, 10, 1), -- Swedish Massage
(4, 11, 1), -- Deep Tissue Massage
(4, 12, 1), -- Airport Transfer - One Way
(4, 13, 1); -- Airport Transfer - Return

-- AdvertisedPackage data
INSERT INTO AdvertisedPackage (Name, Description, StartDate, EndDate, AdvertisedPrice, AdvertisedCurrencyId, StatusId, Inclusions, Exclusions, GracePeriodDays, AuthorizedByEmployeeId, IsStandardPackage, IsActive)
VALUES 
-- Standard packages
('Standard Half-Board', 'Standard room with breakfast included', '2025-01-01', '2025-12-31', 110.00, 1, 1, 'Standard room, Daily breakfast', 'Other meals, Airport transfers', 1, 1, 1, 1),
('Family Getaway', 'Family room with all meals included', '2025-01-01', '2025-12-31', 250.00, 1, 1, 'Family room, All meals', 'Airport transfers, Additional activities', 1, 1, 1, 1),
('Executive Package', 'Executive suite with all meals and airport transfer', '2025-01-01', '2025-12-31', 350.00, 1, 1, 'Executive suite, All meals, Return airport transfer', 'Spa services', 1, 1, 1, 1),

-- Promotional packages
('Summer Escape', '7 nights stay with breakfast and dinner', '2025-06-01', '2025-08-31', 799.00, 1, 1, '7 nights in Standard Room, Daily breakfast and dinner', 'Lunch, Airport transfers', 2, 1, 0, 1),
('Wellness Retreat', '3 nights stay with breakfast and spa treatments', '2025-01-01', '2025-12-31', 599.00, 1, 1, '3 nights in Deluxe Room, Daily breakfast, 2 spa treatments', 'Other meals, Airport transfers', 3, 1, 0, 1),
('Business Traveler', '2 nights stay with breakfast and conference room access', '2025-01-01', '2025-12-31', 399.00, 1, 1, '2 nights in Deluxe Room, Daily breakfast, Half-day conference room', 'Other meals, Airport transfers', 1, 1, 0, 1);

-- PackageServiceItem data
INSERT INTO PackageServiceItem (PackageId, ServiceItemId, Quantity, IsOptional, AdditionalCost)
VALUES 
-- Standard Half-Board
(1, 1, 1, 0, NULL), -- Standard Room
(1, 5, 1, 0, NULL), -- Breakfast Buffet

-- Family Getaway
(2, 3, 1, 0, NULL), -- Family Room
(2, 5, 1, 0, NULL), -- Breakfast Buffet
(2, 6, 1, 0, NULL), -- Lunch Buffet
(2, 7, 1, 0, NULL), -- Dinner Buffet

-- Executive Package
(3, 4, 1, 0, NULL), -- Executive Suite
(3, 5, 1, 0, NULL), -- Breakfast Buffet
(3, 6, 1, 0, NULL), -- Lunch Buffet
(3, 7, 1, 0, NULL), -- Dinner Buffet
(3, 13, 1, 0, NULL), -- Airport Transfer - Return

-- Summer Escape
(4, 1, 7, 0, NULL), -- Standard Room (7 nights)
(4, 5, 7, 0, NULL), -- Breakfast Buffet (7 days)
(4, 7, 7, 0, NULL), -- Dinner Buffet (7 days)

-- Wellness Retreat
(5, 2, 3, 0, NULL), -- Deluxe Room (3 nights)
(5, 5, 3, 0, NULL), -- Breakfast Buffet (3 days)
(5, 10, 1, 0, NULL), -- Swedish Massage
(5, 11, 1, 0, NULL), -- Deep Tissue Massage

-- Business Traveler
(6, 2, 2, 0, NULL), -- Deluxe Room (2 nights)
(6, 5, 2, 0, NULL), -- Breakfast Buffet (2 days)
(6, 8, 1, 0, NULL); -- Half-Day Conference Room

-- HotelPackage data
INSERT INTO HotelPackage (HotelId, PackageId, IsActive)
VALUES 
-- Brisbane Hotel Packages
(1, 1, 1), -- Standard Half-Board
(1, 2, 1), -- Family Getaway
(1, 3, 1), -- Executive Package
(1, 4, 1), -- Summer Escape
(1, 6, 1), -- Business Traveler

-- Cairns Hotel Packages
(2, 1, 1), -- Standard Half-Board
(2, 2, 1), -- Family Getaway
(2, 4, 1), -- Summer Escape

-- Singapore Hotel Packages
(4, 1, 1), -- Standard Half-Board
(4, 3, 1), -- Executive Package
(4, 5, 1), -- Wellness Retreat
(4, 6, 1); -- Business Traveler

-- Customer data
INSERT INTO Customer (FirstName, LastName, Email, PhoneNumber, Address, CityId, LoyaltyPoints, JoinDate, IsActive)
VALUES 
('Robert', 'Jones', 'robert.jones@email.com', '+61-400-111-222', '123 Albert St', 1, 500, '2023-01-15', 1),
('Jennifer', 'Williams', 'jennifer.williams@email.com', '+61-400-222-333', '45 Elizabeth St', 1, 750, '2022-11-10', 1),
('Andrew', 'Clark', 'andrew.clark@email.com', '+61-400-333-444', '78 George St', 2, 250, '2023-03-22', 1),
('Michelle', 'Taylor', 'michelle.taylor@email.com', '+65-9876-5432', '12 Orchard Road', 6, 1000, '2022-06-18', 1),
('Daniel', 'Harris', 'daniel.harris@email.com', '+61-400-444-555', '90 Mitchell St', 5, 100, '2023-05-05', 1);

-- Guest data (some linked to customers, others standalone)
INSERT INTO Guest (FirstName, LastName, Email, PhoneNumber, Address, CityId, CustomerId, IsActive)
VALUES 
-- Guests linked to customers
('Robert', 'Jones', 'robert.jones@email.com', '+61-400-111-222', '123 Albert St', 1, 1, 1),
('Jennifer', 'Williams', 'jennifer.williams@email.com', '+61-400-222-333', '45 Elizabeth St', 1, 2, 1),
('Andrew', 'Clark', 'andrew.clark@email.com', '+61-400-333-444', '78 George St', 2, 3, 1),
('Michelle', 'Taylor', 'michelle.taylor@email.com', '+65-9876-5432', '12 Orchard Road', 6, 4, 1),
('Daniel', 'Harris', 'daniel.harris@email.com', '+61-400-444-555', '90 Mitchell St', 5, 5, 1),

-- Additional guests (not linked to customers)
('Lisa', 'Jones', 'lisa.jones@email.com', '+61-400-111-223', '123 Albert St', 1, 1, 1), -- Robert's spouse
('Tom', 'Williams', 'tom.williams@email.com', '+61-400-222-334', '45 Elizabeth St', 1, 2, 1), -- Jennifer's spouse
('Sarah', 'Taylor', 'sarah.taylor@email.com', '+65-9876-5433', '12 Orchard Road', 6, 4, 1), -- Michelle's child
('Emma', 'Harris', 'emma.harris@email.com', '+61-400-444-556', '90 Mitchell St', 5, 5, 1), -- Daniel's spouse
('Michael', 'Robinson', 'michael.robinson@email.com', '+61-400-555-666', '25 Swanston St', 1, NULL, 1), -- Standalone guest
('Jessica', 'Brown', 'jessica.brown@email.com', '+61-400-666-777', '37 Collins St', 1, NULL, 1); -- Standalone guest